import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy & Terms — Certify",
  description:
    "Legal notice, privacy policy, and cookie policy for Certify.",
  openGraph: {
    title: "Privacy & Terms — Certify",
    description:
      "Legal notice, privacy policy, and cookie policy for Certify.",
  },
};

export default function LegalPage() {
  return (
    <div className="mx-auto flex min-h-full w-full max-w-3xl flex-col px-6 py-20 sm:py-28">
      <main className="flex flex-1 flex-col">
        <header className="border-b border-border pb-10">
          <Link
            href="/"
            className="text-xs font-medium uppercase tracking-[0.32em] text-muted transition-colors hover:text-foreground"
          >
            ← Certify
          </Link>
          <h1 className="mt-8 text-4xl font-semibold leading-[1.1] tracking-tight text-foreground sm:text-5xl">
            Privacy &amp; Terms
          </h1>
          <p className="mt-4 text-sm text-muted">
            Legal notice, privacy policy, and cookie policy.
          </p>
        </header>

        <div className="mt-12 space-y-12">
          {/* 1. Legal Disclaimer */}
          <section>
            <h2 className="text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
              1. Legal Disclaimer &amp; Terms of Use
            </h2>
            <p className="mt-4 text-base leading-relaxed text-foreground/80">
              Certify is an independent utility tool developed for purely
              aesthetic purposes. It is not affiliated with, associated with,
              authorized by, endorsed by, or officially connected to Anthropic
              in any way. The HTML document generated through this service has
              no legal or certifying value. The only official and verifiable
              proof of certification remains the original URL hosted on the
              Skilljar platform. The author assumes no responsibility for the
              alteration, misuse, fraudulent or unlawful use of the files
              generated by users through this platform. By using the service,
              the user accepts these terms.
            </p>
          </section>

          {/* 2. Privacy Policy */}
          <section>
            <h2 className="text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
              2. Privacy Policy
            </h2>
            <p className="mt-4 text-base leading-relaxed text-foreground/80">
              In accordance with the GDPR, please note that using Certify does
              not involve the permanent storage of personal data.
            </p>
            <ul className="mt-5 space-y-4">
              <li className="text-base leading-relaxed text-foreground/80">
                <span className="font-medium text-foreground">
                  Data Controller:
                </span>{" "}
                Tomas Guardati.
              </li>
              <li className="text-base leading-relaxed text-foreground/80">
                <span className="font-medium text-foreground">
                  Data Processed:
                </span>{" "}
                The Skilljar URL provided by the user is processed temporarily
                in memory solely to extract the data needed to generate the
                graphics. No URL or extracted personal data is saved to a
                database or retained after the session is closed.
              </li>
              <li className="text-base leading-relaxed text-foreground/80">
                <span className="font-medium text-foreground">
                  Navigation Data:
                </span>{" "}
                The hosting infrastructure (Vercel) automatically and
                temporarily collects standard connection logs (e.g., IP
                addresses, user agents). This data is necessary to ensure proper
                traffic routing, security, and the technical functioning of the
                service.
              </li>
              <li className="text-base leading-relaxed text-foreground/80">
                <span className="font-medium text-foreground">Sharing:</span>{" "}
                No data is transferred, sold, or shared with third parties for
                marketing or profiling purposes.
              </li>
            </ul>
          </section>

          {/* 3. Cookie Policy */}
          <section>
            <h2 className="text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
              3. Cookie Policy
            </h2>
            <p className="mt-4 text-base leading-relaxed text-foreground/80">
              This website is designed to respect your privacy. We do not use
              profiling cookies, trackers, or third-party analytics tools (e.g.,
              Google Analytics). Only technical cookies or similar technologies
              provided by the hosting infrastructure are used, strictly
              necessary for security and the delivery of the service. For this
              reason, a prior consent banner is not required.
            </p>
          </section>
        </div>
      </main>

      <footer className="mt-16 border-t border-border pt-6">
        <Link
          href="/"
          className="text-xs text-muted underline-offset-4 transition-colors hover:text-foreground hover:underline"
        >
          ← Back to Certify
        </Link>
      </footer>
    </div>
  );
}
