"use client";

import { forwardRef, type CSSProperties } from "react";
import { getAccentColor, getCourseSkills } from "@/lib/courses";

export interface CertificateProps {
  name: string;
  courseTitle: string;
  verifyId: string;
  /** QR code as a data URL (generated by the parent). */
  qrDataUrl?: string;
  /** Issue date string; defaults to today formatted dd/mm/yyyy. */
  issuedOn?: string;
  /** Canvas width in px. Defaults to 1000. */
  width?: number;
  /** Fixed canvas height in px; when set, content is centered to fill it.
   *  Omit/null for the original content-driven height. */
  height?: number | null;
}

const PLAYFAIR = "var(--font-playfair), 'Playfair Display', Georgia, serif";
const INTER = "var(--font-inter), 'Inter', Arial, sans-serif";

/** Formats a date as dd/mm/yyyy to match the certificate template. */
function formatDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()}`;
}

/**
 * The redesigned certificate, adapted from the provided HTML template.
 *
 * Styled with explicit hex colors via inline styles (not Tailwind utilities):
 * Tailwind v4 emits `oklch()` colors, which html2canvas 1.4.1 cannot parse, so
 * inline hex keeps PDF capture reliable. The accent color and skills block are
 * derived from `courseTitle`; the ref points at the capture root.
 */
export const Certificate = forwardRef<HTMLDivElement, CertificateProps>(
  function Certificate(
    { name, courseTitle, verifyId, qrDataUrl, issuedOn, width = 1000, height },
    ref,
  ) {
    const accent = getAccentColor(courseTitle).color;
    const skills = getCourseSkills(courseTitle);
    const issueDate = issuedOn ?? formatDate(new Date());
    const verifyUrl = `https://verify.skilljar.com/c/${verifyId}`;
    const fixedHeight = height ?? null;

    const styles: Record<string, CSSProperties> = {
      container: {
        width,
        ...(fixedHeight ? { height: fixedHeight } : {}),
        backgroundColor: "#Fdfbf7",
        padding: 15,
        boxShadow: "0 10px 30px rgba(0,0,0,0.15)",
        position: "relative",
        boxSizing: "border-box",
        color: "#1A1A1A",
        display: "flex",
        flexDirection: "column",
      },
      border: {
        // The frame fills the canvas (flex: 1). With a fixed height, content is
        // centered so every aspect ratio looks intentional; with content-driven
        // height it sits naturally from the top (the original look). Extra
        // bottom padding gives the footer breathing room above the edge.
        border: `3px solid ${accent}`,
        padding: "50px 70px 60px",
        position: "relative",
        boxSizing: "border-box",
        flex: 1,
        display: "flex",
        flexDirection: "column",
        justifyContent: fixedHeight ? "center" : "flex-start",
      },
      innerBorder: {
        border: `1px solid ${accent}`,
        position: "absolute",
        top: 5,
        bottom: 5,
        left: 5,
        right: 5,
        pointerEvents: "none",
      },
      header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 40,
      },
      logo: {
        fontFamily: PLAYFAIR,
        fontSize: 32,
        fontWeight: 600,
        color: "#1A1A1A",
        letterSpacing: "-0.5px",
        display: "flex",
        alignItems: "center",
        gap: 10,
      },
      certTitle: {
        fontFamily: INTER,
        textTransform: "uppercase",
        letterSpacing: "3px",
        color: "#666",
        fontSize: 14,
        textAlign: "right",
        marginTop: 10,
        paddingRight: 18,
        borderRight: `3px solid ${accent}`,
        lineHeight: 1.4,
      },
      main: { textAlign: "center", marginBottom: 40 },
      issuedTo: {
        fontFamily: INTER,
        fontSize: 14,
        color: "#666",
        textTransform: "uppercase",
        letterSpacing: "2px",
        marginBottom: 15,
      },
      name: {
        fontFamily: PLAYFAIR,
        fontSize: 48,
        color: "#1A1A1A",
        margin: "0 0 15px 0",
        fontStyle: "italic",
      },
      hasCompleted: {
        fontFamily: INTER,
        fontSize: 16,
        color: "#444",
        marginBottom: 20,
      },
      courseName: {
        fontFamily: INTER,
        fontSize: 32,
        fontWeight: 600,
        color: accent,
        margin: 0,
      },
      skills: {
        fontFamily: INTER,
        fontSize: 13,
        color: "#333",
        backgroundColor: "#f7f4ec",
        padding: "25px 40px",
        borderRadius: 4,
        borderLeft: `5px solid ${accent}`,
        margin: "0 auto 40px auto",
        maxWidth: 750,
        textAlign: "left",
      },
      skillsHeading: {
        marginTop: 0,
        marginBottom: 12,
        fontWeight: 600,
        color: "#1a1a1a",
        fontSize: 14,
      },
      skillsList: { margin: 0, paddingLeft: 20, lineHeight: 1.6 },
      footer: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        fontFamily: INTER,
        fontSize: 12,
        color: "#555",
      },
      footerLeft: { display: "flex", gap: 20, alignItems: "center" },
      qr: {
        width: 80,
        height: 80,
        backgroundColor: "#fff",
        border: "1px solid #ccc",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: 10,
        color: "#999",
        padding: 5,
        textAlign: "center",
        boxSizing: "border-box",
        flexShrink: 0,
      },
      signatureBlock: { textAlign: "center", width: 250 },
      signature: {
        fontFamily: PLAYFAIR,
        fontSize: 28,
        color: "#1a1a1a",
        borderBottom: "1px solid #999",
        marginBottom: 8,
        paddingBottom: 5,
        fontStyle: "italic",
      },
      signatureTitle: {
        fontSize: 11,
        textTransform: "uppercase",
        letterSpacing: "1px",
      },
    };

    return (
      <div ref={ref} data-cert-root style={styles.container}>
        <div style={styles.border}>
          <div style={styles.innerBorder} />

          <div style={styles.header}>
            <div style={styles.logo}>
              <svg
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                style={{ width: 35, height: 35 }}
              >
                <path d="M12 2L2 22H6L12 10L18 22H22L12 2Z" fill="#1A1A1A" />
              </svg>
              Anthropic
            </div>
            <div style={styles.certTitle}>
              Certificate of
              <br />
              Course Completion
            </div>
          </div>

          <div style={styles.main}>
            <div style={styles.issuedTo}>
              This certificate is proudly issued to
            </div>
            <h1 style={styles.name}>{name}</h1>
            <div style={styles.hasCompleted}>
              has successfully achieved student level credential for completing
            </div>
            <h2 style={styles.courseName}>{courseTitle}</h2>
          </div>

          <div style={styles.skills}>
            <p style={styles.skillsHeading}>{skills.heading}</p>
            <ul style={styles.skillsList}>
              {skills.items.map((item, i) => (
                <li key={i} style={{ marginBottom: 6 }}>
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div style={styles.footer}>
            <div style={styles.footerLeft}>
              <div style={styles.qr}>
                {qrDataUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={qrDataUrl}
                    alt="QR code to verify certificate"
                    style={{ width: "100%", height: "100%" }}
                  />
                ) : (
                  "QR"
                )}
              </div>
              <div>
                <p style={{ margin: "4px 0" }}>
                  <strong>Issued on:</strong> {issueDate}
                </p>
                <p style={{ margin: "4px 0" }}>
                  <strong>Issued by:</strong> Anthropic (Skilljar Platform)
                </p>
                <p style={{ margin: "4px 0" }}>
                  <strong>Verify:</strong>{" "}
                  <a
                    href={verifyUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ color: accent, textDecoration: "none" }}
                  >
                    {verifyUrl}
                  </a>
                </p>
              </div>
            </div>

            <div style={styles.signatureBlock}>
              <div style={styles.signature}>Anthropic Academy</div>
              <div style={styles.signatureTitle}>Education &amp; Training Team</div>
            </div>
          </div>
        </div>
      </div>
    );
  },
);
