"use client";

import { forwardRef, type CSSProperties } from "react";
import { getAccentColor, getCourseSkills } from "@/lib/courses";

export interface CertificateProps {
  name: string;
  courseTitle: string;
  verifyId: string;
  /** QR code as a data URL (generated by the parent). */
  qrDataUrl?: string;
  /** Issue date string; defaults to today formatted dd/mm/yyyy. */
  issuedOn?: string;
  /** Canvas width in px. Defaults to 1000. */
  width?: number;
  /** Fixed canvas height in px; when set, content is centered to fill it.
   *  Omit/null for the original content-driven height. */
  height?: number | null;
}

const PLAYFAIR = "var(--font-playfair), 'Playfair Display', Georgia, serif";
const INTER = "var(--font-inter), 'Inter', Arial, sans-serif";

/** Formats a date as dd/mm/yyyy to match the certificate template. */
function formatDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()}`;
}

/**
 * The redesigned certificate, adapted from the provided HTML template.
 *
 * Styled with explicit hex colors via inline styles (not Tailwind utilities):
 * Tailwind v4 emits `oklch()` colors, which html2canvas 1.4.1 cannot parse, so
 * inline hex keeps PDF capture reliable. The accent color and skills block are
 * derived from `courseTitle`; the ref points at the capture root.
 *
 * Two layout modes:
 *  - **Portrait/standard** (content-driven height): the original look — type at
 *    its natural sizes, sections stacked from the top.
 *  - **Landscape** (a fixed height much wider than it is tall, e.g. 16:9): type
 *    and spacing scale up so the design fills the larger canvas instead of
 *    floating small in the middle, and the skills render in two columns to use
 *    the width and keep the block short enough to fit the reduced height.
 */
export const Certificate = forwardRef<HTMLDivElement, CertificateProps>(
  function Certificate(
    { name, courseTitle, verifyId, qrDataUrl, issuedOn, width = 1000, height },
    ref,
  ) {
    const accent = getAccentColor(courseTitle).color;
    const skills = getCourseSkills(courseTitle);
    const issueDate = issuedOn ?? formatDate(new Date());
    const verifyUrl = `https://verify.skilljar.com/c/${verifyId}`;
    const fixedHeight = height ?? null;

    // Landscape mode kicks in when the canvas is markedly wider than it is tall
    // (16:9 ≈ 1.78). There, the standard type sizes look lost, so everything
    // scales up by `s` and the skills go two-up. Portrait keeps `s = 1` so the
    // standard certificate is byte-for-byte unchanged.
    const isWide = fixedHeight != null && width / fixedHeight >= 1.4;
    const s = isWide ? 1.1 : 1;
    const px = (n: number) => Math.round(n * s);

    // Spacing between the header / body / footer bands. Landscape packs tighter
    // (relative to its larger type) so the scaled-up content still fits the
    // shorter canvas and reads as one cohesive block.
    const bandGap = isWide ? px(16) : 40;

    // Usable content width inside the frame (container + frame padding). The
    // skills block widens with the canvas so wide formats don't leave empty
    // side bands, but never exceeds the frame.
    const frameContentWidth = width - px(30) - px(140);
    const skillsMaxWidth = Math.min(
      Math.round(750 * (width / 1000)),
      frameContentWidth,
    );

    const styles: Record<string, CSSProperties> = {
      container: {
        width,
        ...(fixedHeight ? { height: fixedHeight } : {}),
        backgroundColor: "#Fdfbf7",
        padding: px(15),
        boxShadow: "0 10px 30px rgba(0,0,0,0.15)",
        position: "relative",
        boxSizing: "border-box",
        color: "#1A1A1A",
        display: "flex",
        flexDirection: "column",
      },
      border: {
        // The frame fills the canvas (flex: 1). With a fixed height the three
        // bands are vertically centered as one block; the scaled-up content is
        // sized to nearly fill the frame, so the margins above and below stay
        // small and even — intentional, like the standard. Content-driven
        // height keeps the original top-aligned stack.
        border: `3px solid ${accent}`,
        padding: isWide
          ? `${px(38)}px ${px(70)}px ${px(42)}px`
          : "50px 70px 60px",
        position: "relative",
        boxSizing: "border-box",
        flex: 1,
        display: "flex",
        flexDirection: "column",
        gap: bandGap,
        justifyContent: fixedHeight ? "center" : "flex-start",
      },
      innerBorder: {
        border: `1px solid ${accent}`,
        position: "absolute",
        top: 5,
        bottom: 5,
        left: 5,
        right: 5,
        pointerEvents: "none",
      },
      header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-start",
      },
      // Groups the name/course block and the skills block so the frame can
      // distribute header / body / footer as three even bands.
      middle: {
        display: "flex",
        flexDirection: "column",
        gap: bandGap,
      },
      logo: {
        fontFamily: PLAYFAIR,
        fontSize: px(32),
        fontWeight: 600,
        color: "#1A1A1A",
        letterSpacing: "-0.5px",
        display: "flex",
        alignItems: "center",
        gap: px(10),
      },
      certTitle: {
        fontFamily: INTER,
        textTransform: "uppercase",
        letterSpacing: "3px",
        color: "#666",
        fontSize: px(14),
        textAlign: "right",
        marginTop: px(10),
        paddingRight: px(18),
        borderRight: `3px solid ${accent}`,
        lineHeight: 1.4,
      },
      main: { textAlign: "center" },
      issuedTo: {
        fontFamily: INTER,
        fontSize: px(14),
        color: "#666",
        textTransform: "uppercase",
        letterSpacing: "2px",
        marginBottom: px(15),
      },
      name: {
        fontFamily: PLAYFAIR,
        fontSize: px(48),
        color: "#1A1A1A",
        margin: `0 0 ${px(15)}px 0`,
        fontStyle: "italic",
      },
      hasCompleted: {
        fontFamily: INTER,
        fontSize: px(16),
        color: "#444",
        marginBottom: px(20),
      },
      courseName: {
        fontFamily: INTER,
        fontSize: px(32),
        fontWeight: 600,
        color: accent,
        margin: 0,
      },
      skills: {
        fontFamily: INTER,
        fontSize: px(13),
        color: "#333",
        backgroundColor: "#f7f4ec",
        padding: `${px(25)}px ${px(40)}px`,
        borderRadius: 4,
        borderLeft: `${px(5)}px solid ${accent}`,
        margin: "0 auto",
        maxWidth: skillsMaxWidth,
        width: "100%",
        boxSizing: "border-box",
        textAlign: "left",
      },
      skillsHeading: {
        marginTop: 0,
        marginBottom: px(12),
        fontWeight: 600,
        color: "#1a1a1a",
        fontSize: px(14),
      },
      skillsList: isWide
        ? {
            margin: 0,
            // Two columns in landscape: fills the width and halves the height.
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            columnGap: px(40),
            rowGap: px(4),
            listStylePosition: "inside",
            paddingLeft: 0,
            lineHeight: 1.6,
          }
        : { margin: 0, paddingLeft: 20, lineHeight: 1.6 },
      footer: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "flex-end",
        fontFamily: INTER,
        fontSize: px(12),
        color: "#555",
      },
      footerLeft: { display: "flex", gap: px(20), alignItems: "center" },
      qr: {
        width: px(80),
        height: px(80),
        backgroundColor: "#fff",
        border: "1px solid #ccc",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: px(10),
        color: "#999",
        padding: px(5),
        textAlign: "center",
        boxSizing: "border-box",
        flexShrink: 0,
      },
      signatureBlock: { textAlign: "center", width: px(250) },
      signature: {
        fontFamily: PLAYFAIR,
        fontSize: px(28),
        color: "#1a1a1a",
        borderBottom: "1px solid #999",
        marginBottom: px(8),
        paddingBottom: px(5),
        fontStyle: "italic",
      },
      signatureTitle: {
        fontSize: px(11),
        textTransform: "uppercase",
        letterSpacing: "1px",
      },
    };

    return (
      <div ref={ref} data-cert-root style={styles.container}>
        <div style={styles.border}>
          <div style={styles.innerBorder} />

          <div style={styles.header}>
            <div style={styles.logo}>
              <svg
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                style={{ width: px(35), height: px(35) }}
              >
                <path d="M12 2L2 22H6L12 10L18 22H22L12 2Z" fill="#1A1A1A" />
              </svg>
              Anthropic
            </div>
            <div style={styles.certTitle}>
              Certificate of
              <br />
              Course Completion
            </div>
          </div>

          <div style={styles.middle}>
            <div style={styles.main}>
              <div style={styles.issuedTo}>
                This certificate is proudly issued to
              </div>
              <h1 style={styles.name}>{name}</h1>
              <div style={styles.hasCompleted}>
                has successfully achieved student level credential for completing
              </div>
              <h2 style={styles.courseName}>{courseTitle}</h2>
            </div>

            <div style={styles.skills}>
              <p style={styles.skillsHeading}>{skills.heading}</p>
              <ul style={styles.skillsList}>
                {skills.items.map((item, i) => (
                  <li key={i} style={{ marginBottom: px(6) }}>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div style={styles.footer}>
            <div style={styles.footerLeft}>
              <div style={styles.qr}>
                {qrDataUrl ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={qrDataUrl}
                    alt="QR code to verify certificate"
                    style={{ width: "100%", height: "100%" }}
                  />
                ) : (
                  "QR"
                )}
              </div>
              <div>
                <p style={{ margin: `${px(4)}px 0` }}>
                  <strong>Issued on:</strong> {issueDate}
                </p>
                <p style={{ margin: `${px(4)}px 0` }}>
                  <strong>Issued by:</strong> Anthropic (Skilljar Platform)
                </p>
                <p style={{ margin: `${px(4)}px 0` }}>
                  <strong>Verify:</strong>{" "}
                  <a
                    href={verifyUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{ color: accent, textDecoration: "none" }}
                  >
                    {verifyUrl}
                  </a>
                </p>
              </div>
            </div>

            <div style={styles.signatureBlock}>
              <div style={styles.signature}>Anthropic Academy</div>
              <div style={styles.signatureTitle}>Education &amp; Training Team</div>
            </div>
          </div>
        </div>
      </div>
    );
  },
);
